### ISSUE TITLE
Move project gofn to organization gofn

### ISSUE THREAD

**Issue by avelino** [gofn/gofn#94]
I understand that the project was created by Nuveo (which is why it was born within the organization Nuveo).
Looking for the future of the project we have many seas to navigate (several opportunities to make the project grow and earn its own life).

What's your opinion on moving to [gofn organization](https://github.com/gofn)?

**Comment by crgimenes** [comment]
I like the idea

**Comment by cassiobotaro** [comment]
SGTM, let's do it!

**Comment by perylemke** [comment]
It's a good idea!

**Comment by lerrua** [comment]
Sounds good to me. :+1:

**Comment by kemelzaidan** [comment]
I'm not so sure about it... I believe that for projects beginning it's life, gives confidence to know that there is at least a company using and improving it. After the project has taken off and gained life on it's own, it's easier to handle the governance to the community. But doing it now, before growing a community around it sounds as just a cosmetic change, since Nuveo is the only organization that will deal with it anyways.

**Comment by avelino** [comment]
@kemelzaidan I understand your vision, see another reason I proposed this change: #95
